name: main

on:
  push:
    branches:
      - main

jobs:
  linux_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Show settings and generate random files"
        run: |
          set | grep GITHUB_ | grep -v GITHUB_TOKEN
          zip -r pkg.zip *.md
          mkdir -p test/subdir
          echo "$(openssl rand -hex 6)" > "test/subdir/random-name-linux-$(openssl rand -hex 6).txt"
          echo "$(openssl rand -hex 6)" > "test/subdir/random-name-linux-$(openssl rand -hex 6).txt"
          echo "$(openssl rand -hex 6)" > "test/subdir/absulote-path-test-linux.txt"
      - uses: xresloader/upload-to-github-release@main
        with:
          file: "*.md;*.zip;test/subdir/random-name-linux-*.txt;${{ github.workspace }}/test/subdir/absulote-path-test-linux.txt"
          delete_file: "*linux*.txt"
          branches: "main;dev"
          verbose: true
          prerelease: true
          default_release_name: "Test release name for main branch"
          default_release_body: "Test release body for main branch"
  windows_test:
    runs-on: windows-latest
    needs: [linux_test]
    steps:
      - uses: actions/checkout@v3
      - name: "Show settings and generate random files"
        shell: bash
        run: |
          set | grep GITHUB_ | grep -v GITHUB_TOKEN
          mkdir -p test/subdir
          echo "$(openssl rand -hex 6)" > "test/subdir/random-name-windows-$(openssl rand -hex 6).txt"
          echo "$(openssl rand -hex 6)" > "test/subdir/random-name-windows-$(openssl rand -hex 6).txt"
          echo "$(openssl rand -hex 6)" > "test/subdir/absulote-path-test-windows.txt"
      - uses: xresloader/upload-to-github-release@main
        with:
          file: "test\\subdir\\random-name-windows-*.txt;${{ github.workspace }}\\test\\subdir\\absulote-path-test-windows.txt"
          delete_file: "*windows*.txt"
          branches: "main;dev"
          verbose: true
          prerelease: true
          default_release_name: "Test release name for main branch"
