name: main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "find env"
        run: |
          set | grep GITHUB_ | grep -v GITHUB_TOKEN
          zip -r pkg.zip *.md
          echo "$(openssl rand -hex 6)" > "random-name-$(openssl rand -hex 6).txt"
          echo "$(openssl rand -hex 6)" > "random-name-$(openssl rand -hex 6).txt"
      - uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.md;*.zip;random-name-*.txt"
          delete_file: "random-name-*.txt"
          branches: "main;dev"
          verbose: true
          prerelease: true
