name: main

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: xresloader/upload-to-github-release@master
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        file: "*.md"
        tags: true
        draft: true
