name: main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "find env"
      run: |
        set | grep GITHUB_ | grep -v GITHUB_TOKEN
        zip -r pkg.zip *.md
    - uses: xresloader/upload-to-github-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "*.md;*.zip"
        tags: true
        draft: true
        branches: "master;dev"
